# Generated by Django 3.2.8 on 2021-11-04 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_activate', models.DateTimeField(default=datetime.datetime(2022, 11, 4, 17, 44, 13, 211475))),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
